import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";

/** @type {import('eslint').Linter.Config[]} */
export default [
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,js}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "array-bracket-spacing": ["error", "always", { "singleValue": true, "objectsInArrays": true, "arraysInArrays": true }],
      "comma-spacing": ["error", { "before": false, "after": true }],
      "object-curly-spacing": ["error", "always"],
      "key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
      "no-irregular-whitespace": 0,
      "semi": ["error", "always"],
      "indent": ["error", "tab"],
      "no-const-assign": "error",
      "no-dupe-keys": "warn",
      "no-unreachable": "error",
      "camelcase": "warn",
      "no-tabs": "off",
      "one-var": "off",
      "object-curly-newline": "off",
      "padded-blocks": "off",
      "space-before-function-paren": "off",
      "no-var": "error",
      "arrow-spacing": "error",
      "no-prototype-builtins": "off",
      "no-undef": "off",
      "no-cond-assign": "off",
      "no-constant-condition": "off",
      "no-console": "warn",
      "no-debugger": "warn",
      "array-callback-return": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-throw-literal": "error",
      "no-shadow": "warn",
      "eqeqeq": "warn",
      "quotes": ["error", "single"],
      "no-mixed-requires": "error",
      "no-new-require": "error",
      "arrow-parens": ["error", "always"],
      "prefer-const": "error",
      "eol-last": "off",
      "space-infix-ops": ["error", { "int32Hint": false }],
      "space-before-blocks": ["error", "always"],
      "keyword-spacing": ["error", { "before": true, "after": true }],
      "space-in-parens": ["error", "never"],
      "comma-dangle": ["error", "never"],
      "no-multi-spaces": "error",
      "no-trailing-spaces": "error",
      "no-multiple-empty-lines": ["error", { "max": 1, "maxEOF": 0 }],
      "no-whitespace-before-property": "error",
      "block-spacing": ["error", "always"],
      "brace-style": ["error", "1tbs", { "allowSingleLine": true }],
      "curly": ["error", "multi-line"],
      "max-len": ["warn", { "code": 1000, "ignoreUrls": true, "ignoreStrings": true, "ignoreTemplateLiterals": true }],
      "no-unused-vars": "error",
      "@typescript-eslint/no-unused-vars": ["warn", { "args": "after-used", "ignoreRestSiblings": true, "varsIgnorePattern": "^_" }]
    }
  }
];
