import path from 'path';
import fs from 'fs';

export const RESPONSE_MESSAGES = {
	UNAUTHORIZED: 'UNAUTHORIZED',
	SUCCESS: 'SUCCESS',
	USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	INVALID_PASSWORD: 'INVALID_PASSWORD',
	INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
	INVALID_TOKEN: 'INVALID_TOKEN',
	TOUR_SKIPPED_SUCCESSFULLY: 'TOUR_SKIPPED_SUCCESSFULLY',
	ERROR_REGISTERING_USER: 'ERROR_REGISTERING_USER',
	LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
	LOGOUT_SUCCESSFUL: 'LOGOUT_SUCCESSFUL',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	INVALID_EMAIL: 'INVALID_EMAIL',
	PLEASE_VERIFY_YOUR_EMAIL: 'PLEASE_VERIFY_YOUR_EMAIL',
	RESET_LINK_SENT: 'RESET_LINK_SENT',
	INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
	PASSWORD_CHANGED_SUCCESSFULLY: 'PASSWORD_CHANGED_SUCCESSFULLY',
	EMAIL_SENT_TO_YOUR_EMAIL: 'EMAIL_SENT_TO_YOUR_EMAIL',
	GOOGLE_TOKEN_MUST_MATCH_WITH_REGISTERED_EMAIL: 'GOOGLE_TOKEN_MUST_MATCH_WITH_REGISTERED_EMAIL',
	INVALID_OTP: 'INVALID_OTP',
	EMAIL_VERIFIED_SUCCESSFULLY: 'EMAIL_VERIFIED_SUCCESSFULLY',
	TOKEN_EXPIRED_ERROR: 'TOKEN_EXPIRED_ERROR',
	EMAIL_VERIFICATION_NOT_REQUESTED: 'EMAIL_VERIFICATION_NOT_REQUESTED',
	AGE_NOT_ENOUGH: 'AGE_NOT_ENOUGH',
	USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY',
	GOOGLE_SIGIN_FAILED: 'GOOGLE_SIGIN_FAILED',
	APPLE_SIGIN_FAILED: 'APPLE_SIGIN_FAILED',
	FACEBOOK_SIGIN_FAILED: 'FACEBOOK_SIGIN_FAILED',
	USER_NOT_ADDED_IN_NEWS_FOLLOW_UP: 'USER_NOT_ADDED_IN_NEWS_FOLLOW_UP',
	USER_ADDED_IN_NEWS_FOLLOW_UP: 'USER_ADDED_IN_NEWS_FOLLOW_UP',
	USER_REMOVED_FROM_NEWS_FOLLOW_UP: 'USER_REMOVED_FROM_NEWS_FOLLOW_UP',
	FILE_NOT_FOUND: 'FILE_NOT_FOUND',
	FILE_UPLOADED_SUCCESSFULLY: 'FILE_UPLOADED_SUCCESSFULLY',
	FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
	FILE_DELETED_SUCCESSFULLY: 'FILE_DELETED_SUCCESSFULLY',
	FILE_NOT_DELETED: 'FILE_NOT_DELETED',
	INVALID_FILE_URL: 'INVALID_FILE_URL',
	INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
	INVALID_FILE_SIZE: 'INVALID_FILE_SIZE',
	PROFILE_CREATED_SUCCESSFULLY: 'PROFILE_CREATED_SUCCESSFULLY',
	PROFILE_DOES_NOT_EXIST: 'PROFILE_DOES_NOT_EXIST',
	MEASUREMENT_DOES_NOT_EXIST: 'MEASUREMENT_DOES_NOT_EXIST',
	MEASUREMENT_ALREADY_PREDICTED: 'MEASUREMENT_ALREADY_PREDICTED',
	PROFILE_UPDATED_SUCCESSFULLY: 'PROFILE_UPDATED_SUCCESSFULLY',
	LANGUAGE_UPDATED_SUCCESSFULLY: 'LANGUAGE_UPDATED_SUCCESSFULLY',
	PLEASE_SELECT_VALID_LANGUAGE: 'PLEASE_SELECT_VALID_LANGUAGE',
	PLEASE_SELECT_PREFFERED_LANGUAGE: 'PLEASE_SELECT_PREFERRED_LANGUAGE',
	PROFILE_DELETED_SUCCESSFULLY: 'PROFILE_DELETED_SUCCESSFULLY',
	DATA_FETCHED_SUCCESSFULLY: 'DATA_FETCHED_SUCCESSFULLY',
	USER_DELETED_SUCCESSFULLY: 'USER_DELETED_SUCCESSFULLY',
	TRY_AFTER_SOMETIME: 'TRY_AFTER_SOMETIME',
	ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
	CAR_NOT_FOUND: 'CAR_NOT_FOUND',
	CAR_CREATED_SUCCESSFULLY: 'CAR_CREATED_SUCCESSFULLY',
	CAR_UPDATED_SUCCESSFULLY: 'CAR_UPDATED_SUCCESSFULLY',
	CAR_DELETED_SUCCESSFULLY: 'CAR_DELETED_SUCCESSFULLY'
};

export const ERROR_TYPES = {
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	BAD_REQUEST: 'BAD_REQUEST',
	UNAUTHORIZED: 'UNAUTHORIZED',
	DATA_NOT_FOUND: 'DATA_NOT_FOUND',
	MONGO_EXCEPTION: 'MONGO_EXCEPTION',
	ALREADY_EXISTS: 'ALREADY_EXISTS',
	FORBIDDEN: 'FORBIDDEN'
};

export const STATUS_CODES = {
	SUCCESS: 200,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	DATA_NOT_FOUND: 404,
	ALREADY_EXISTS: 400,
	INTERNAL_SERVER_ERROR: 500,
	FORBIDDEN: 403
};

export const EMAIL_TYPES = {
	WELCOME_EMAIL: 1,
	FORGOT_PASSWORD_EMAIL: 2,
	REGISTER_COMPLETE: 3,
	STAFF_CREDENTIALS: 4
};

export const GENDERS = {
	MALE: 1,
	FEMALE: 2,
	NON_BINARY: 3
};

export const LOGIN_TYPE = {
	NORMAL: 1,
	GOOGLE: 2,
	APPLE: 3,
	FACEBOOK: 4
};

export const DATABASE_VERSIONS = {
	ONE: 1,
	TWO: 2
};

export const AVAILABLE_AUTHS = {
	ADMIN: 1,
	USER: 2,
	ADMIN_OR_USER: 3,
	USER_WITH_DATA_RELAXATION: 4
};

export const AVAILABLE_WEBHOOK_AUTHS = {
	AI: 1
};

export const EMAIL_SUBJECTS = {
	FORGOT_PASSWORD_EMAIL: 'Reset your password',
	WELCOME_EMAIL: 'Welcome to Attendance System',
	REGISTER_COMPLETE: 'Welcome to Attendance System',
	STAFF_CREDENTIALS: 'Your Staff Account Credentials - Attendance System'
};

export const UPLOAD_FILE_TYPE = {
	USER_PROFILE: 1,
};

export const EMAIL_CONTENTS = {
	FORGOT_PASSWORD_EMAIL: fs.readFileSync(path.join(__dirname, '../../public/templates/forgotPassword.html'), { encoding: 'utf-8' }),
	WELCOME_EMAIL: fs.readFileSync(path.join(__dirname, '../../public/templates/welcomeOnboard.html'), { encoding: 'utf-8' }),
	REGISTER_COMPLETE: fs.readFileSync(path.join(__dirname, '../../public/templates/registerCompleted.html'), { encoding: 'utf-8' }),
	STAFF_CREDENTIALS: fs.readFileSync(path.join(__dirname, '../../public/templates/staffCredentials.html'), { encoding: 'utf-8' })
};

export const SPECIAL_CHARACTERS = ['~', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '-', '_', '+', '=', '{', '}', '[', ']', '|', '/', ':', ';', '"', '\'', '<', '>', ',', '.', '?'];

export const USER_STATUS = {
	ACTIVE: 1,
	INACTIVE: 2
};

export const LANGUAGE = {
	ENGLISH: 1
};

export const REGEX = {
	PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[ !"#$%&'()*+,/:;<=>?@[\]^_`{|}~÷°¬±µ‰¤ƒ¥€£¢ß¿¡©®™§†‡—¶])(?=.{8,})/,
	TIME: /^([01]\d|2[0-3]):([0-5]\d)$/,
	PHONE: /^\+?[1-9]\d{1,14}$/,
	COUNTRY_CODE: /^\+\d{1,3}$/
};

export const USER_ROLE = {
	ADMIN: 'admin',
	USER: 'user',
	STAFF: 'staff'
};

export const USER_VALIDATION_CHECK = { registrationInComplete: { $exists: false }, isVerified: true, status: USER_STATUS.ACTIVE };

export const USER_VALIDATION_CHECK_WITH_ROLE = { registrationInComplete: { $exists: false }, status: USER_STATUS.ACTIVE, role: USER_ROLE.USER };

export const ERROR_LOGS_TYPES = {
	SERVER_ERROR: 1,
	AI_IMAGE_GENERATION_FAILED: 2,
	SERVER_FAILED: 3,
	REQUEST_TIMED_OUT: 4,
	MEASUREMENT_PREDICTION_FAILED: 5,
	APPLE_SIGIN_FAILED: 6,
	FACEBOOK_SIGIN_FAILED: 7,
	GOOGLE_SIGIN_FAILED: 8
};

export const USER_TYPES = {
	OWNER: 1,
};